version: '2'
services:
  matrix:
    build:
      context: .
      dockerfile: ./matrix/.stack-work/image/0
      depends_on:
        - fpco/stack-run 
        - fpco/stack-build
      restart: always
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    explorer:
      build:
        context: .
        dockerfile: ./matrix-explorer/Dockerfile
        depends_on: ubuntu
        expose: 
          - "5000"
        port: 
          - "8545:8545"
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
